import { Inter } from "next/font/google";
import "./globals.css";
import { Box } from "@mui/material";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: any = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-secondary01">
        <Navbar />
        <Box className="bg-neutral01 mx-10 my-5 h-screen items-center rounded-2xl">
          {children}
        </Box>
      </body>
    </html>
  );
}
